# -*- coding: utf-8 -*-

"""
Define terms contained in various standard controlled vocabularies.
"""

from __future__ import unicode_literals


# Collective title terms, adapted from RDA and AACR2 rules. Note that
# these aren't exhaustive, as both rulesets allow for things other
# than these.
COLLECTIVE_TITLE_TERMS = set((
    'correspondence',
    'essays',
    'librettos',
    'lyrics',
    'novels',
    'plays',
    'poems',
    'prose works',
    'short stories',
    'speeches',
    'works'
))

# Music form terms, adapted from http://cmc.blog.musiclibraryassoc.org/
# types-of-composition-for-use-in-authorized-access-points-for-music-
# complete-list/
# Structure of the terms list is (singular form, (plural forms)).
MUSIC_FORM_TERMS = (
    ('adagietto', ('adagiettos',)),
    ('adagio', ('adagios',)),
    ('agnus dei', tuple()),
    ('air', ('airs',)),
    ('aire', ('aires',)),
    ('allegretto', ('allegrettos',)),
    ('allegro', ('allegros',)),
    ('allemande', ('allemandes',)),
    ('andante', ('andantes',)),
    ('andantino', ('andantinos',)),
    ('anglaise', ('anglaises',)),
    ('anthem', ('anthems',)),
    ('arabesque', ('arabesques',)),
    ('aria', ('arias',)),
    ('arietta', ('ariettas',)),
    ('ariettina', ('ariettinas',)),
    ('arioso', ('ariosos',)),
    ('aubade', ('aubades',)),
    ('ave maria', tuple()),
    ('ayre', ('ayres',)),
    ('bagatelle', ('bagatelles',)),
    ('balada', ('baladas',)),
    ('ballad', ('ballads',)),
    ('ballade', ('ballades',)),
    ('ballade', ('ballades',)),
    ('ballata', ('ballate', 'ballatas',)),
    ('ballett', ('balletts',)),
    ('balletto', ('balletti',)),
    ('bambuco', ('bambucos',)),
    ('barcarolle', ('barcarolles',)),
    ('barcarollette', ('barcarollettes',)),
    ('basse danse', tuple()),
    ('beguine', ('beguines',)),
    ('berceuse', ('berceuses',)),
    ('beweging', ('bewegingen',)),
    ('bicinium', ('bicinia',)),
    ('blues', tuple()),
    ('bolero', ('boleros',)),
    ('bossa nova', tuple()),
    ('bourrée', ('bourrées',)),
    ('boutade', tuple()),
    ('burla', ('burlas',)),
    ('burlesque', ('burlesques',)),
    ('cadenza', ('cadenzas',)),
    ('canary', ('canaries',)),
    ('canción', ('canciones',)),
    ('canon', ('canons',)),
    ('cantabile', ('cantabiles',)),
    ('cantata', ('cantatas',)),
    ('canticle', ('canticles',)),
    ('cantiga', ('cantigas',)),
    ('canto', ('canti', 'cantos')),
    ('canzona', ('canzonas',)),
    ('canzonet', ('canzonets',)),
    ('canzonetta', ('canzonettas',)),
    ('capriccetto', ('capriccetti',)),
    ('capriccietto', ('capriccietti',)),
    ('capriccio', ('capriccios',)),
    ('caprice', ('caprices',)),
    ('capricette', ('capricetten',)),
    ('carmen', ('carmina',)),
    ('carol', ('carols',)),
    ('cassation', ('cassations',)),
    ('catch', ('catches',)),
    ('cavatina', ('cavatinas',)),
    ('chacarera', ('chacareras',)),
    ('chaconne', ('chaconnes',)),
    ('chamber music', tuple()),
    ('chanson', ('chansons',)),
    ('chant', ('chants',)),
    ('chast\'', ('chasti',)),
    ('choralbearbeitung', ('choralbearbeitungen',)),
    ('chorale prelude', ('chorale preludes',)),
    ('chorale', ('chorales',)),
    ('choralvorspiel', ('choralvorspiele',)),
    ('choral-vorspiel', ('choral-vorspiele',)),
    ('chorinho', ('chorinhos',)),
    ('choro', ('choros',)),
    ('chorus', ('choruses',)),
    ('cibell', ('cibells',)),
    ('composition', ('compositions',)),
    ('concertante', ('concertantes',)),
    ('concertino', ('concertinos',)),
    ('concerto grosso', ('concerti grossi',)),
    ('concerto', ('concertos',)),
    ('concertone', ('concertoni',)),
    ('conductus', tuple()),
    ('conga', ('congas',)),
    ('cortège', ('cortèges',)),
    ('country dance', ('country dances',)),
    ('courante', ('courantes',)),
    ('cradle song', tuple()),
    ('credo', tuple()),
    ('czardas', ('czardas',)),
    ('dal', ('dalok',)),
    ('dance', ('dances',)),
    ('danza', ('danzas',)),
    ('darab', ('darabok',)),
    ('decet', ('decets',)),
    ('divertimentino', ('divertimentinos',)),
    ('divertimento', ('divertimenti',)),
    ('division', ('divisions',)),
    ('division on a ground', ('divisions on a ground',)),
    ('double canon', ('double canons',)),
    ('double fugue', ('double fugues',)),
    ('duet', ('duets',)),
    ('duettino', ('duettinos',)),
    ('dumka', ('dumkas',)),
    ('dump', ('dumps',)),
    ('duodecet', ('duodecets',)),
    ('ecossaise', ('ecossaises',)),
    ('elegietta', ('elegiettas',)),
    ('elegy', ('elegies',)),
    ('entr\'acte', ('entr\'actes',)),
    ('equale', ('equali',)),
    ('estampie', ('estampies',)),
    ('estudio', ('estudios',)),
    ('ėtiud', ('ėtiudy',)),
    ('etüde', ('etüden',)),
    ('etude', ('etudes',)),
    ('étude', ('études',)),
    ('exercise', ('exercises',)),
    ('fancy', ('fancies',)),
    ('fandango', ('fandangos',)),
    ('fandanguillo', ('fandanguillos',)),
    ('fanfare', ('fanfares',)),
    ('fantaisie', ('fantaisies',)),
    ('fantasi', ('fantasier',)),
    ('fantasia-suite', ('fantasia-suites',)),
    ('fantasia', ('fantasias',)),
    ('fantasía', ('fantasías',)),
    ('fantasia', ('fantasie',)),
    ('fantasie', ('fantasien',)),
    ('fantasietta', ('fantasiettas',)),
    ('fantasio', tuple()),
    ('fantasy', ('fantasies',)),
    ('finale', ('finales',)),
    ('flourish', ('flourishes',)),
    ('forlane', tuple()),
    ('foxtrot', ('foxtrots',)),
    ('frottola', ('frottolas',)),
    ('fugato', ('fugatos',)),
    ('fughetta', ('fughettas',)),
    ('fugue', ('fugues',)),
    ('furiant', ('furiants',)),
    ('galliard', ('galliards',)),
    ('galop', ('galops',)),
    ('gavotte', ('gavottes',)),
    ('gesang', ('gesänge',)),
    ('gigue', ('gigues',)),
    ('glásba', tuple()),
    ('glee', ('glees',)),
    ('gletta', ('glettur',)),
    ('gloria', tuple()),
    ('gradual', ('graduals',)),
    ('graduale', tuple()),
    ('graduále', tuple()),
    ('graduel', tuple()),
    ('ground', ('grounds',)),
    ('guajira', ('guajiras',)),
    ('gyakorlat', ('gyakorlatok',)),
    ('habanera', ('habaneras',)),
    ('harmony', ('harmonies',)),
    ('hornpipe', ('hornpipes',)),
    ('hudba', tuple()),
    ('humoresque', ('humoresques',)),
    ('hymn', ('hymns',)),
    ('impromptu', ('impromptus',)),
    ('improvisation', ('improvisations',)),
    ('in nomine', ('in nomines',)),
    ('induló', ('indulók',)),
    ('interlude', ('interludes',)),
    ('intermède', ('intermèdes',)),
    ('intermezzo', ('intermezzi',)),
    ('intonation', ('intonations',)),
    ('intrada', ('intradas',)),
    ('introduction', ('introductions',)),
    ('introit', ('introits',)),
    ('invention', ('inventions',)),
    ('jácara', ('jácaras',)),
    ('jota', ('jotas',)),
    ('kappale', ('kappaletta',)),
    ('kehtolaulu', ('kehtolaulut',)),
    ('kettős fúga', ('kettős fúgak',)),
    ('kettős', ('kettősök',)),
    ('kołysanka', ('kołysanki',)),
    ('krakowiak', ('krakowiaks',)),
    ('kujawiak', ('kujawiaks',)),
    ('kyrie', tuple()),
    ('ländler', ('ländler',)),
    ('larghetto', ('larghettos',)),
    ('largo', ('largos',)),
    ('laulu', ('laulut',)),
    ('lectura', ('lecturas',)),
    ('lecture', ('lectures',)),
    ('lento', tuple()),
    ('lesson', ('lessons',)),
    ('lesung', ('lesungen',)),
    ('lied', ('lieder',)),
    ('lullaby', ('lullabies',)),
    ('madrigal', ('madrigals',)),
    ('maestoso', tuple()),
    ('magnificat', ('magnificats',)),
    ('malagueña', ('malagueñas',)),
    ('mambo', ('mambos',)),
    ('march', ('marches',)),
    ('marcietta', ('marciettas',)),
    ('mass', ('masses',)),
    ('mazurka', ('mazurkas',)),
    ('mélodie', ('mélodies',)),
    ('melody', ('melodies',)),
    ('milonga', ('milongas',)),
    ('minuet', ('minuets',)),
    ('miserere', tuple()),
    ('moderato', ('moderatos',)),
    ('modinha', ('modinhas',)),
    ('morceau', ('morceaux',)),
    ('motet', ('motets',)),
    ('movement', ('movements',)),
    ('musette', ('musettes',)),
    ('music', ('musicals',)),
    ('nachspiel', ('nachspiele',)),
    ('négyes', ('négyesek',)),
    ('nocturne', ('nocturnes',)),
    ('noël', ('noëls',)),
    ('nonet', ('nonets',)),
    ('oberek', ('oberki',)),
    ('octet', ('octets',)),
    ('ode', ('odes',)),
    ('offertorium', tuple()),
    ('offertory', ('offertories',)),
    ('ostinato', ('ostinatos',)),
    ('overture', ('overtures',)),
    ('pala', ('palad',)),
    ('part song', ('part songs',)),
    ('part-song', ('part-songs',)),
    ('partsong', ('partsongs',)),
    ('partita', ('partitas',)),
    ('paseo', ('paseos',)),
    ('paso', ('pasos',)),
    ('pasodoble', ('pasodobles',)),
    ('passacaglia', ('passacaglias',)),
    ('passamezzo', ('passamezzos',)),
    ('passepied', ('passepieds',)),
    ('pastoral', ('pastorals',)),
    ('pastorale', ('pastorales',)),
    ('pastorella', ('pastorellas',)),
    ('pavan', ('pavans',)),
    ('pavanilla', ('pavanillas',)),
    ('pesem', ('pesmi',)),
    ('pesen', ('pesni',)),
    ('phantasia', ('phantasias',)),
    ('phantasie', ('phantasien',)),
    ('phantasy', ('phantasies',)),
    ('piece', ('pieces',)),
    ('pisen', ('pisne',)),
    ('piva', ('pive',)),
    ('pjesma', ('pjesme',)),
    ('polacca', ('polaccas',)),
    ('polka', ('polkas',)),
    ('polonaise', ('polonaises',)),
    ('postlude', ('postludes',)),
    ('potpourri', ('potpourris',)),
    ('předehra', ('předehry',)),
    ('prelude', ('preludes',)),
    ('prestissimo', ('prestissimos',)),
    ('presto', ('prestos',)),
    ('processional', ('processionals',)),
    ('psalm', ('psalms',)),
    ('quadrille', ('quadrilles',)),
    ('quartet', ('quartets',)),
    ('quartettino', ('quartettinos',)),
    ('quintet', ('quintets',)),
    ('quintettino', ('quintettinos',)),
    ('quodlibet', ('quodlibets',)),
    ('rag', ('rags',)),
    ('recessional', ('recessionals',)),
    ('récit', ('récits',)),
    ('recitative', ('recitatives',)),
    ('requiem', ('requiems',)),
    ('rhapsody', ('rhapsodies',)),
    ('ricercare', ('ricercars', 'ricercari')),
    ('rigaudon', ('rigaudons',)),
    ('ritornello', ('ritornelli',)),
    ('ritournelle', ('ritournelles',)),
    ('romance', ('romances',)),
    ('romans', ('romansy',)),
    ('romanza', ('romanzas',)),
    ('romanza', ('romanze',)),
    ('romanze', ('romanzen',)),
    ('romanzetta', ('romanzettas',)),
    ('rondeau', ('rondeaux',)),
    ('rondino', ('rondinos',)),
    ('rondo', ('rondos',)),
    ('rondoletto', ('rondolettos',)),
    ('round', ('rounds',)),
    ('rumba', ('rumbas',)),
    ('rundgesang', ('rundgesänge',)),
    ('saltarello', ('saltarellos',)),
    ('salve regina', tuple()),
    ('samba', ('sambas',)),
    ('samospev', ('samospevi',)),
    ('sanctus', tuple()),
    ('saraband', ('sarabands',)),
    ('sardana', ('sardanas',)),
    ('satz', ('sätze',)),
    ('sbor', ('sbory',)),
    ('scherzando', ('scherzandos',)),
    ('scherzettino', ('scherzettinos',)),
    ('scherzetto', ('scherzetti',)),
    ('scherzino', ('scherzinos',)),
    ('scherzo', ('scherzos',)),
    ('seguidilla', ('seguidillas',)),
    ('septet', ('septets',)),
    ('serenade', ('serenades',)),
    ('seresta', ('serestas',)),
    ('service', ('services',)),
    ('set', ('sets',)),
    ('sett', ('setts',)),
    ('sevillana', ('sevillanas',)),
    ('sextet', ('sextets',)),
    ('siciliana', ('sicilianas',)),
    ('simphonie concertante', ('simphonies concertantes',)),
    ('sinfonia concertante', ('sinfonie concertanti',)),
    ('sinfonia', ('sinfonie',)),
    ('sinfonie concertante', ('sinfonies concertantes',)),
    ('sinfonietta concertante', ('sinfoniette concertanti',)),
    ('sinfonietta', ('sinfoniettas',)),
    ('sinfonische dichtung', ('sinfonische dichtungen',)),
    ('sinfonische gedicht', ('sinfonische gedichte',)),
    ('skladba', ('skladby',)),
    ('solfeggietto', ('solfeggietti',)),
    ('solfeggio', ('solfeggios',)),
    ('solo', ('solos',)),
    ('son', ('sones',)),
    ('sonata movement', ('sonata movements',)),
    ('sonata', ('sonatas',)),
    ('sonatensatz', ('sonatensätze',)),
    ('sonatille', ('sonatilles',)),
    ('sonatina', ('sonatinas',)),
    ('sonatinetta', ('sonatinettas',)),
    ('song', ('songs',)),
    ('sousedská', ('sousedsky',)),
    ('spiritual', ('spirituals',)),
    ('stabat mater', tuple()),
    ('ständchen', tuple()),
    ('strophe', ('strophen',)),
    ('stück', ('stücke',)),
    ('stückchen', tuple()),
    ('studie', ('studien',)),
    ('studio', ('studi',)),
    ('study', ('studies',)),
    ('stuk', ('stukken',)),
    ('suite', ('suites',)),
    ('symphonette', ('symphonettes',)),
    ('symphonic poem', ('symphonic poems',)),
    ('symphonie concertante', ('symphonies concertantes',)),
    ('symphonische dichtung', ('symphonische dichtungen',)),
    ('symphony concertante', ('symphonies concertantes',)),
    ('symphony', ('symphonies',)),
    ('tambourin', ('tambourins',)),
    ('tango', ('tangos',)),
    ('tanulmány', ('tanulmányok',)),
    ('tarantella', ('tarantellas',)),
    ('te deum', tuple()),
    ('terzettino', ('terzettinos',)),
    ('tétel', ('tételek',)),
    ('theme', ('themes',)),
    ('tiento', ('tientos',)),
    ('tirana', ('tiranas',)),
    ('toccata', ('toccatas',)),
    ('toccatella', ('toccatellas',)),
    ('toccatina', ('toccatinas',)),
    ('tondichtung', ('tondichtungen',)),
    ('toy', ('toys',)),
    ('tricinium', ('tricinia',)),
    ('trio sonata', ('trio sonatas',)),
    ('trio', ('trios',)),
    ('trioletto', ('triolettos',)),
    ('trumpet tune', ('trumpet tunes',)),
    ('tune', ('tunes',)),
    ('tuutulaulu', ('tuutulaulut',)),
    ('übung', ('übungen',)),
    ('ukolébavka', ('ukolébavky',)),
    ('undecet', ('undecets',)),
    ('utwór', ('utwory',)),
    ('variation', ('variations',)),
    ('veränderung', ('veränderungen',)),
    ('verse', ('verses',)),
    ('verset', ('versets',)),
    ('vesper', ('vespers',)),
    ('villancico', ('villancicos',)),
    ('villanella', ('villanelle',)),
    ('villanelle', ('villanelles',)),
    ('virelai', ('virelais',)),
    ('vivace', ('vivaces',)),
    ('vivo', ('vivos',)),
    ('vocalise', ('vocalises',)),
    ('volta', ('volte',)),
    ('voluntary', ('voluntaries',)),
    ('vorspiel', ('vorspiele',)),
    ('vuggevise', ('vuggeviser',)),
    ('waltz', ('waltzes',)),
    ('wiegenlied', ('wiegenlieder',)),
    ('zamba', ('zambas',)),
    ('zapateado', ('zapateados',)),
    ('zene', ('zenék',)),
    ('zortzico', ('zortzicos',)),
    ('zpĕv', ('zpĕvy',)),
    ('zwiefacher', ('zwiefache',)),
    ('zwischenakt', ('zwischenakten',)),
    ('zwischenspiel', ('zwischenspiele')),
)

MUSIC_FORM_TERMS_DICT = {entry[0]: entry[1] for entry in MUSIC_FORM_TERMS}
MUSIC_FORM_TERMS_SINGULAR = set((entry[0] for entry in MUSIC_FORM_TERMS))
MUSIC_FORM_TERMS_PLURAL = set((pl for en in MUSIC_FORM_TERMS for pl in en[1]))
MUSIC_FORM_TERMS_ALL = MUSIC_FORM_TERMS_SINGULAR | MUSIC_FORM_TERMS_PLURAL
