name: Build and compose docker images, run tests
on: [push, workflow_dispatch]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v4
      - name: set CI environment variables
        run: mv django/sierra/sierra/settings/docker-ci.env django/sierra/sierra/settings/.env
      - name: pull external service images via docker-compose
        run: |
          ./docker-compose.sh pull default-db-test sierra-db-test \
            solr-test-for-update solr-test-for-search \
            redis-celery-test redis-appdata-test
      - name: build our docker image and services
        run: ./docker-compose.sh build manage-test celery-worker-test test
      - name: configure data volumes and build databases
        run: ./init-dockerdata.sh tests
      - name: run all tests
        run: ./docker-compose.sh run --rm test
